#!/bin/bash

# Chemin vers le fichier de configuration SSH
SSHD_CONFIG="/etc/ssh/sshd_config"
SUDOERS_FILE="/etc/sudoers"

# Remplacer les lignes dans le fichier sshd_config
sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' $SSHD_CONFIG
sed -i 's/#PubkeyAuthentication yes/PubkeyAuthentication yes/' $SSHD_CONFIG
sed -i 's/#AuthorizedKeysFile\s\+.ssh\/authorized_keys\s\+.ssh\/authorized_keys2/AuthorizedKeysFile     .ssh\/authorized_keys .ssh\/authorized_keys2/' $SSHD_CONFIG
sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' $SSHD_CONFIG

# Redémarrer le service SSH
systemctl restart sshd

# Ajouter la ligne debian ALL=(ALL:ALL) ALL dans le fichier sudoers après la section "User privilege specification"
if ! grep -q "^debian\s\+ALL=(ALL:ALL) ALL" $SUDOERS_FILE; then
    sed -i '/# User privilege specification/a debian    ALL=(ALL:ALL) ALL' $SUDOERS_FILE
fi

# Créer les dossiers .ssh et les fichiers authorized_keys pour root et debian
mkdir -p /root/.ssh
touch /root/.ssh/authorized_keys
chmod 700 /root/.ssh
chmod 600 /root/.ssh/authorized_keys

mkdir -p /home/debian/.ssh
touch /home/debian/.ssh/authorized_keys
chmod 700 /home/debian/.ssh
chmod 600 /home/debian/.ssh/authorized_keys
chown -R debian:debian /home/debian/.ssh

# Ajouter les clés SSH dans les fichiers authorized_keys pour root et debian
SSH_KEYS="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHrDMU4abJhX5TL57TBKTxTdJQiLFrWcP8EhAOkIsnQC EdR0Z@github/102168399 # ssh-import-id gh:EdR0Z
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINAvUilbFU5wwh+3q1gedc9W2dIWzcT6giOwR58y5iEr ed25519-key-20240613
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOrE9/aeGwH4XZ6c0AfCVE+JCD7zKnTh7b4Jd+XV+/oP Generated By Termius"

# Ajouter les clés au fichier /root/.ssh/authorized_keys
if ! grep -q "${SSH_KEYS}" /root/.ssh/authorized_keys; then
    echo "$SSH_KEYS" >> /root/.ssh/authorized_keys
fi

# Ajouter les clés au fichier /home/debian/.ssh/authorized_keys
if ! grep -q "${SSH_KEYS}" /home/debian/.ssh/authorized_keys; then
    echo "$SSH_KEYS" >> /home/debian/.ssh/authorized_keys
fi

echo "Modifications effectuées, dossiers .ssh créés, clés ajoutées et service SSH redémarré."
